version: '3'
services:
  api:
    image: 'node:12.19.0'
    working_dir: /api
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - PGUSER=chris
      - PGHOST=db
      - PGPASSWORD=presDB57
      - PGDATABASE=presents
      - PGPORT=5432
    depends_on: 
      - db
    volumes:
      - type: bind
        source: api
        target: /api
    command: bash -c "npm install && npm run seedDev && npm run dev"
  db:
    image: 'postgres:latest'
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=presents
      - POSTGRES_USER=chris
      - POSTGRES_PASSWORD=presDB57
volumes:
  dbdata: